package com.dbp.legalcheck.common.enums;

public enum LawyerSpecialization {
    DERECHO_CONSTITUCIONAL,
    DERECHO_PENAL,
    DERECHO_ADMINISTRATIVO,
    DERECHO_PROCESAL,
    DERECHO_LABORAL,
    DERECHO_INTERNACIONAL_PÚBLICO,
    DERECHO_CIVIL,
    DERECHO_MERCANTIL,
    DERECHO_INTERNACIONAL_PRIVADO,
    DERECHO_DE_LA_SEGURIDAD_SOCIAL,
    DERECHO_AGRARIO
}
